# GPT From Scratch
Changes

In [1]:
import torch

### Tiny Shakespeare - Input dataset

In [2]:
with open('input/shakespeare.txt', 'r', encoding= 'utf- 8') as f:
    text = f.read()

In [3]:
chars = sorted(list(set(text)))
vocab_size = len(chars)

In [4]:
stoi = {ch:i for i, ch in enumerate(chars)}
itos = {i:ch for i, ch in enumerate(chars)}

encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

print(encode('hello'))
print(decode([46, 43, 50, 50, 53]))

[46, 43, 50, 50, 53]
hello


In [5]:
data = torch.tensor(encode(text), dtype= torch.long)
print(data.shape, data.dtype)
print(data[:100])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [6]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [52]:
batch_size = 4      # Number of blocks to be processed parallely
block_size = 8      # Maximum context window for our transformer

def split(dataset):
    data = train_data if dataset == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))  # Arg1-> range, not inclusive of the upper cap, Arg2 -> Size which is a tuple to allow n dimensional tensor output
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = split('train')
print(xb.shape)
print(xb)
print(yb.shape)
print(yb)

torch.Size([4, 8])
tensor([[ 5, 57,  1, 45, 53, 53, 42, 50],
        [21,  1, 61, 53, 59, 50, 42,  1],
        [46, 43, 56,  5, 57,  1, 50, 47],
        [46,  1, 61, 43, 39, 50, 58, 46]])
torch.Size([4, 8])
tensor([[57,  1, 45, 53, 53, 42, 50, 63],
        [ 1, 61, 53, 59, 50, 42,  1, 58],
        [43, 56,  5, 57,  1, 50, 47, 44],
        [ 1, 61, 43, 39, 50, 58, 46,  1]])
